name: verify

on: push

env:
  TZ: America/Indianapolis

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: mvn verify
      run: mvn verify

